package com.istar.mediabroken.console

import com.istar.mediabroken.entity.account.Account
import com.istar.mediabroken.entity.capture.Site
import com.istar.mediabroken.repo.account.AccountRepo
import com.istar.mediabroken.repo.capture.SiteRepo
import com.istar.mediabroken.service.capture.SiteService
import com.istar.mediabroken.utils.DateUitl
import com.istar.mediabroken.utils.ExportExcel
import groovy.util.logging.Slf4j
import org.apache.commons.io.FileUtils
import org.apache.http.HttpStatus
import org.apache.poi.hssf.usermodel.HSSFWorkbook
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import java.text.SimpleDateFormat

@Component
@Slf4j
public class SiteListByDateConsole implements Console {
    @Autowired
    SiteService siteService
    @Autowired
    SiteRepo siteRepo
    @Autowired
    AccountRepo accountRepo

    @Override
    public void execute(Map properties) {
        //1148家站点去重后的url
        def urlsMap = [
                "zzwb.zynews.cn"                     : "1",
                "zyue.com"                           : "1",
                "zuzhirenshi.com"                    : "1",
                "zqrb.ccstock.cn"                    : "1",
                "zqb.cyol.com"                       : "1",
                "zol.com.cn"                         : "1",
                "zohi.tv"                            : "1",
                "zjrb.zjol.com.cn"                   : "1",
                "zhyww.cn"                           : "1",
                "zgg.org.cn"                         : "1",
                "zgdsw.org.cn"                       : "1",
                "zaozhuang.dzwww.com"                : "1",
                "zaobao.com"                         : "1",
                "yzwb.sjzdaily.com.cn"               : "1",
                "yndaily.yunnan.cn"                  : "1",
                "yicai.com"                          : "1",
                "yhnews.zjol.com.cn"                 : "1",
                "yesky.com"                          : "1",
                "xnwbw.com"                          : "1",
                "xmzk.xinminweekly.com.cn"           : "1",
                "xmwb.xinmin.cn"                     : "1",
                "xmtv.cn"                            : "1",
                "xjdaily.com"                        : "1",
                "xinwen.eluosi.cn"                   : "1",
                "xh.xhby.net"                        : "1",
                "xfrb.com.cn"                        : "1",
                "wynews.zjol.com.cn"                 : "1",
                "www.zzradio.cn"                     : "1",
                "www.zznews.gov.cn"                  : "1",
                "www.zyrb.com.cn"                    : "1",
                "www.zxxww.com"                      : "1",
                "www.zwskw.com"                      : "1",
                "www.zuzhirenshi.com"                : "1",
                "www.ztnews.net"                     : "1",
                "www.zsbtv.com.cn"                   : "1",
                "www.zohi.tv"                        : "1",
                "www.zjstv.com"                      : "1",
                "www.zjol.com.cn"                    : "1",
                "www.zjknews.com"                    : "1",
                "www.zjgrrb.com"                     : "1",
                "www.zhzyw.org"                      : "1",
                "www.zgzyw.com.cn"                   : "1",
                "www.zgxqds.com"                     : "1",
                "www.zgswcn.com"                     : "1",
                "www.zgkashi.com"                    : "1",
                "www.zgjtb.com"                      : "1",
                "www.zgjrjw.com"                     : "1",
                "www.zgfznews.com"                   : "1",
                "www.zaobao.com"                     : "1",
                "www.yygcj.com"                      : "1",
                "www.yyfensi.com"                    : "1",
                "www.yuxinews.com"                   : "1",
                "www.yushunews.com"                  : "1",
                "www.yunnan.cn"                      : "1",
                "www.yuloo.com"                      : "1",
                "www.yododo.cn"                      : "1",
                "www.ynradio.com"                    : "1",
                "www.ylxw.com.cn"                    : "1",
                "www.ykwin.com"                      : "1",
                "www.yidianzixun.com"                : "1",
                "www.yicai.com"                      : "1",
                "www.yhcm.org"                       : "1",
                "www.yescar.cn"                      : "1",
                "www.yellowriver.gov.cn"             : "1",
                "www.ycwb.com"                       : "1",
                "www.ycgbtv.com.cn"                  : "1",
                "www.yangsheng.com"                  : "1",
                "www.yahoo.com"                      : "1",
                "www.xywy.com"                       : "1",
                "www.xtrb.cn"                        : "1",
                "www.xnwbw.com"                      : "1",
                "www.xmtv.cn"                        : "1",
                "www.xmnn.cn"                        : "1",
                "www.xjtvs.com.cn"                   : "1",
                "www.xjbs.com.cn"                    : "1",
                "www.xinwenquan.org"                 : "1",
                "www.xinjiangyaou.com"               : "1",
                "www.xinhuanet.com/mil/"             : "1",
                "www.xinhuanet.com"                  : "1",
                "www.xingtai.gov.cn"                 : "1",
                "www.xincheping.com"                 : "1",
                "www.xilu.com"                       : "1",
                "www.xfrb.com.cn"                    : "1",
                "www.xdkb.net"                       : "1",
                "www.wyzxwk.com"                     : "1",
                "www.wxrb.com"                       : "1",
                "www.workercn.cn"                    : "1",
                "www.women.org.cn"                   : "1",
                "www.wj001.com"                      : "1",
                "www.webcars.com.cn"                 : "1",
                "www.weather.com.cn"                 : "1",
                "www.wccdaily.com.cn"                : "1",
                "www.vtibet.com"                     : "1",
                "www.vodjk.com"                      : "1",
                "www.voc.com.cn"                     : "1",
                "www.viewcn.com"                     : "1",
                "www.un.org"                         : "1",
                "www.tynews.com.cn"                  : "1",
                "www.twwtn.com"                      : "1",
                "www.ttys5.com"                      : "1",
                "www.traveldaily.cn"                 : "1",
                "www.toptour.cn"                     : "1",
                "www.tongliaowang.com"               : "1",
                "www.tlnews.com.cn"                  : "1",
                "www.tlnews.cn"                      : "1",
                "www.time-weekly.com"                : "1",
                "www.tianjinwe.com"                  : "1",
                "www.tianjin.gov.cn"                 : "1",
                "www.thetimes.co.uk"                 : "1",
                "www.thepaper.cn"                    : "1",
                "www.thebeijingnews.com"             : "1",
                "www.tcnews.cc"                      : "1",
                "www.taiwan.cn"                      : "1",
                "www.szwb.info"                      : "1",
                "www.sznews.com"                     : "1",
                "www.syd.com.cn"                     : "1",
                "www.sxsm.com.cn"                    : "1",
                "www.sxrtv.com"                      : "1",
                "www.sxrb.com"                       : "1",
                "www.sxllnews.cn"                    : "1",
                "www.sxhctv.com"                     : "1",
                "www.sxcm.net"                       : "1",
                "www.swqq.net"                       : "1",
                "www.swissinfo.ch"                   : "1",
                "www.suv.cn"                         : "1",
                "www.subaonet.com"                   : "1",
                "www.stnn.cc"                        : "1",
                "www.stdaily.com"                    : "1",
                "www.srxww.com"                      : "1",
                "www.sq1996.com"                     : "1",
                "www.spiegel.de"                     : "1",
                "www.southcn.com"                    : "1",
                "www.sootoo.com"                     : "1",
                "www.sohu.com"                       : "1",
                "www.smg.cn"                         : "1",
                "www.sina.com.cn"                    : "1",
                "www.shxb.net"                       : "1",
                "www.shuaijiao.com"                  : "1",
                "www.shenchuang.com"                 : "1",
                "www.shanxigov.cn"                   : "1",
                "www.sdpy.gov.cn"                    : "1",
                "www.sdpc.gov.cn"                    : "1",
                "www.sdnews.com.cn"                  : "1",
                "www.sdde.gov.cn"                    : "1",
                "www.sctv.com"                       : "1",
                "www.scnjnews.com"                   : "1",
                "www.sanqin.com"                     : "1",
                "www.rmlt.com.cn"                    : "1",
                "www.radiotj.com"                    : "1",
                "www.qzwb.com"                       : "1",
                "www.qx818.com"                      : "1",
                "www.qnsb.com"                       : "1",
                "www.qlwb.com.cn"                    : "1",
                "www.qjrb.cn"                        : "1",
                "www.qingdaonews.com"                : "1",
                "www.qianzhan.com"                   : "1",
                "www.qhnews.com"                     : "1",
                "www.qhdnews.com"                    : "1",
                "www.qhbtv.com"                      : "1",
                "www.qguiyang.cn"                    : "1",
                "www.qdxw.com.cn"                    : "1",
                "www.qdaily.com"                     : "1",
                "www.ptxw.com"                       : "1",
                "www.prcfe.com"                      : "1",
                "www.peoplerail.com"                 : "1",
                "www.peoplechina.com.cn"             : "1",
                "www.outlookweekly.cn"               : "1",
                "www.oushinet.com"                   : "1",
                "www.nytsyn.com"                     : "1",
                "www.nxtv.com.cn"                    : "1",
                "www.northtimes.com"                 : "1",
                "www.nnwb.com"                       : "1",
                "www.nnrb.com.cn"                    : "1",
                "www.nnnews.net"                     : "1",
                "www.nmtv.cn"                        : "1",
                "www.nmgcb.com.cn"                   : "1",
                "www.njgb.com"                       : "1",
                "www.njdaily.cn"                     : "1",
                "www.nhfpc.gov.cn"                   : "1",
                "www.ngzb.com.cn"                    : "1",
                "www.nfcmag.com"                     : "1",
                "www.newsyc.com"                     : "1",
                "www.newsweek.com"                   : "1",
                "www.newhua.com"                     : "1",
                "www.ndwww.cn"                       : "1",
                "www.ndrc.gov.cn"                    : "1",
                "www.nbtv.cn"                        : "1",
                "www.nbs.cn"                         : "1",
                "www.nbd.com.cn"                     : "1",
                "www.naxww.com"                      : "1",
                "www.mytaizhou.net"                  : "1",
                "www.myrb.net"                       : "1",
                "www.mxrb.cn"                        : "1",
                "www.morningpost.com.cn"             : "1",
                "www.mofcom.gov.cn"                  : "1",
                "www.mof.gov.cn"                     : "1",
                "www.moe.edu.cn"                     : "1",
                "www.modernweekly.com"               : "1",
                "www.mnw.cn"                         : "1",
                "www.mm111.net"                      : "1",
                "www.metalnews.cn"                   : "1",
                "www.mencius.gov.cn"                 : "1",
                "www.meizhou.cn"                     : "1",
                "www.mafengwo.cn"                    : "1",
                "www.m4.cn"                          : "1",
                "www.lztv.tv"                        : "1",
                "www.lzep.cn"                        : "1",
                "www.lyg01.net"                      : "1",
                "www.ly.com"                         : "1",
                "www.lwzg.net.cn"                    : "1",
                "www.lvmama.com"                     : "1",
                "www.luaninfo.com"                   : "1",
                "www.lsxw.gov.cn"                    : "1",
                "www.ls666.com"                      : "1",
                "www.lqxww.com"                      : "1",
                "www.lotour.com"                     : "1",
                "www.lnd.com.cn"                     : "1",
                "www.liangjan.com"                   : "1",
                "www.lhrb.com.cn"                    : "1",
                "www.leshan.cn"                      : "1",
                "www.legaldaily.com.cn"              : "1",
                "www.lc-news.com"                    : "1",
                "www.langya.cn"                      : "1",
                "www.laivx.com"                      : "1",
                "www.laifeng.net"                    : "1",
                "www.ksnews.cn"                      : "1",
                "www.kmtv.com.cn"                    : "1",
                "www.kgong.cn"                       : "1",
                "www.kepuchina.cn"                   : "1",
                "www.kcna.kp"                        : "1",
                "www.jzxww.com.cn"                   : "1",
                "www.jznews.com.cn"                  : "1",
                "www.jygxw.com"                      : "1",
                "www.jyb.cn"                         : "1",
                "www.jxnn.cn"                        : "1",
                "www.jxnews.com.cn"                  : "1",
                "www.jwb.com.cn"                     : "1",
                "www.js7tv.cn"                       : "1",
                "www.jn001.com"                      : "1",
                "www.jlradio.cn"                     : "1",
                "www.jlntv.cn"                       : "1",
                "www.jkb.com.cn"                     : "1",
                "www.jjckb.cn"                       : "1",
                "www.jiazhao.com"                    : "1",
                "www.jiajia.net"                     : "1",
                "www.jfdaily.com"                    : "1",
                "www.jcrb.com"                       : "1",
                "www.itxinwen.com"                   : "1",
                "www.ittime.com.cn"                  : "1",
                "www.iqilu.com"                      : "1",
                "www.inhe.net"                       : "1",
                "www.infzm.com"                      : "1",
                "www.iheima.com"                     : "1",
                "www.icswb.com"                      : "1",
                "www.iceo.com.cn"                    : "1",
                "www.ibtimes.com.cn"                 : "1",
                "www.hxnews.com"                     : "1",
                "www.huoshannews.com"                : "1",
                "www.huizhou.cn"                     : "1",
                "www.huabian.com"                    : "1",
                "www.hsrb.com.cn"                    : "1",
                "www.hqrw.com.cn"                    : "1",
                "www.hqck.net"                       : "1",
                "www.hnnews.cc"                      : "1",
                "www.hljtv.com"                      : "1",
                "www.hljradio.com"                   : "1",
                "www.hkcna.hk"                       : "1",
                "www.hhhtnews.com"                   : "1",
                "www.hgdaily.com.cn"                 : "1",
                "www.henandaily.cn"                  : "1",
                "www.hcxcw.com"                      : "1",
                "www.hbyunyang.net"                  : "1",
                "www.hbenshi.gov.cn"                 : "1",
                "www.haodf.com"                      : "1",
                "www.hanzhongnews.cn"                : "1",
                "www.gzstv.com"                      : "1",
                "www.gznet.com"                      : "1",
                "www.gz163.com.cn"                   : "1",
                "www.gyxww.cn"                       : "1",
                "www.gxylnews.com"                   : "1",
                "www.gxnews.com.cn"                  : "1",
                "www.guoxue.com"                     : "1",
                "www.guandian.cn"                    : "1",
                "www.guancha.cn"                     : "1",
                "www.gs.chinanews.com"               : "1",
                "www.greenchina.tv"                  : "1",
                "www.gov.cn"                         : "1",
                "www.gog.cn"                         : "1",
                "www.gndaily.com"                    : "1",
                "www.gmw.cn"                         : "1",
                "www.gjnews.cn"                      : "1",
                "www.ggnews.com.cn"                  : "1",
                "www.gfdy.gov.cn"                    : "1",
                "www.genshuixue.com"                 : "1",
                "www.gdtv.cn"                        : "1",
                "www.gdnews.gov.cn"                  : "1",
                "www.gangu.gov.cn"                   : "1",
                "www.fynews.com.cn"                  : "1",
                "www.fxrbs.cn"                       : "1",
                "www.fxingw.com"                     : "1",
                "www.fx120.net"                      : "1",
                "www.ftchinese.com"                  : "1",
                "www.fqxww.cn"                       : "1",
                "www.fqlook.com"                     : "1",
                "www.foshannews.net"                 : "1",
                "www.fortunechina.com"               : "1",
                "www.fmprc.gov.cn"                   : "1",
                "www.fjtv.net"                       : "1",
                "www.fjsen.com"                      : "1",
                "www.fjqlw.com"                      : "1",
                "www.fjii.com"                       : "1",
                "www.financialnews.com.cn"           : "1",
                "www.fengxiannews.com"               : "1",
                "www.farmer.com.cn"                  : "1",
                "www.eyh.cn"                         : "1",
                "www.enshi.cn"                       : "1",
                "www.enet.com.cn"                    : "1",
                "www.eeo.com.cn"                     : "1",
                "www.edu.cn"                         : "1",
                "www.ebusinessreview.cn"             : "1",
                "www.ebrun.com"                      : "1",
                "www.e0734.com"                      : "1",
                "www.dzxw.net"                       : "1",
                "www.dzwww.com"                      : "1",
                "www.dtxw.cn"                        : "1",
                "www.drc.gov.cn"                     : "1",
                "www.dnkb.com.cn"                    : "1",
                "www.dlxww.com"                      : "1",
                "www.dltv.cn"                        : "1",
                "www.diaoyu123.com"                  : "1",
                "www.dehua.net"                      : "1",
                "www.ddcpc.cn"                       : "1",
                "www.dangjian.cn/"                   : "1",
                "www.dailyqd.com"                    : "1",
                "www.cztv.com"                       : "1",
                "www.cznews.gov.cn"                  : "1",
                "www.ctw.cn"                         : "1",
                "www.csytv.com"                      : "1",
                "www.csxww.com"                      : "1",
                "www.csbtv.com"                      : "1",
                "www.cs.com.cn"                      : "1",
                "www.crntt.com"                      : "1",
                "www.cri.com.cn"                     : "1",
                "www.cqwb.com.cn"                    : "1",
                "www.cqrb.cn"                        : "1",
                "www.cqn.com.cn"                     : "1",
                "www.cqcb.com"                       : "1",
                "www.cpd.com.cn"                     : "1",
                "www.cnxww.cn"                       : "1",
                "www.cnxw.com.cn"                    : "1",
                "www.cntv.cn"                        : "1",
                "www.cntour.cn"                      : "1",
                "www.cnstock.com"                    : "1",
                "www.cnr.cn"                         : "1",
                "www.cnqiang.com"                    : "1",
                "www.cnnb.com.cn"                    : "1",
                "www.cnii.com.cn"                    : "1",
                "www.cnhubei.com"                    : "1",
                "www.cn-healthcare.com"              : "1",
                "www.cnhan.com/html/whwb"            : "1",
                "www.cnhan.com/html/cjrb"            : "1",
                "www.cnhan.com"                      : "1",
                "www.cnchu.com"                      : "1",
                "www.cnautonews.com"                 : "1",
                "www.clssn.com"                      : "1",
                "www.cjn.cn"                         : "1",
                "www.cicn.com.cn"                    : "1",
                "www.chunyuyisheng.com"              : "1",
                "www.chiznews.com"                   : "1",
                "www.chinesetoday.com"               : "1",
                "www.chinaxwcb.com"                  : "1",
                "www.chinawznews.net"                : "1",
                "www.chinawater.com.cn/slb"          : "1",
                "www.chinaventure.com.cn"            : "1",
                "www.chinavalue.net"                 : "1",
                "www.chinatradenews.com.cn"          : "1",
                "www.chinatibetnews.com"             : "1",
                "www.chinareports.org.cn"            : "1",
                "www.chinaqw.com"                    : "1",
                "www.chinaqking.com"                 : "1",
                "www.chinapostnews.com.cn"           : "1",
                "www.chinajsb.cn"                    : "1",
                "www.chinadevelopmentbrief.org.cn"   : "1",
                "www.chinadaily.com.cn"              : "1",
                "www.chinactv.com"                   : "1",
                "www.chinacdc.cn"                    : "1",
                "www.chinabgao.com"                  : "1",
                "www.chexun.com"                     : "1",
                "www.chewen.com"                     : "1",
                "www.chengshiw.com"                  : "1",
                "www.cfnews.gov.cn"                  : "1",
                "www.cfgw.net.cn"                    : "1",
                "www.cfen.com.cn"                    : "1",
                "www.ceweekly.cn"                    : "1",
                "www.ceocio.com.cn"                  : "1",
                "www.centv.cn"                       : "1",
                "www.ce.cn"                          : "1",
                "www.cdrb.com.cn"                    : "1",
                "www.cditv.cn"                       : "1",
                "www.ccwqtv.com"                     : "1",
                "www.cctv.com"                       : "1",
                "www.ccs.cn"                         : "1",
                "www.ccoalnews.com"                  : "1",
                "www.ccn.com.cn"                     : "1",
                "www.ccdy.cn"                        : "1",
                "www.ccdi.gov.cn"                    : "1",
                "www.cbinews.com"                    : "1",
                "www.cb.com.cn"                      : "1",
                "www.cankaoxiaoxi.com"               : "1",
                "www.caigou2003.com"                 : "1",
                "www.cac.gov.cn"                     : "1",
                "www.bynrnews.com"                   : "1",
                "www.btzx.com.cn"                    : "1",
                "www.brtn.cn"                        : "1",
                "www.bndaily.com"                    : "1",
                "www.bkxww.com"                      : "1",
                "www.bjnews.com.cn"                  : "1",
                "www.bjd.com.cn"                     : "1",
                "www.bjcpn.com"                      : "1",
                "www.beijingreview.com.cn"           : "1",
                "www.beijing.gov.cn"                 : "1",
                "www.bbnews.cn"                      : "1",
                "www.bbaqw.com"                      : "1",
                "www.bashan.com"                     : "1",
                "www.baotounews.com.cn"              : "1",
                "www.bamaol.com"                     : "1",
                "www.babytree.com"                   : "1",
                "www.audit.gov.cn"                   : "1",
                "www.asahi.com"                      : "1",
                "www.aqsc.cn"                        : "1",
                "www.aqnews.com.cn"                  : "1",
                "www.anqiunews.com"                  : "1",
                "www.anhuinews.com"                  : "1",
                "www.altxw.com"                      : "1",
                "www.aljazeera.net"                  : "1",
                "www.aisixiang.com"                  : "1",
                "www.ahtv.cn"                        : "1",
                "www.ahssnews.com"                   : "1",
                "www.ahrtv.cn"                       : "1",
                "www.aba-news.com.cn"                : "1",
                "www.99.com.cn"                      : "1",
                "www.8264.com"                       : "1",
                "www.71.cn"                          : "1",
                "www.360che.com"                     : "1",
                "www.1m3d.com"                       : "1",
                "www.199it.com"                      : "1",
                "www.12371.cn"                       : "1",
                "www.0817tv.com"                     : "1",
                "www.0730news.com"                   : "1",
                "www.010lf.com"                      : "1",
                "world.people.com.cn"                : "1",
                "world.chinadaily.com.cn"            : "1",
                "wlnews.zjol.com.cn/wlrb/"           : "1",
                "whwb.cjn.cn"                        : "1",
                "whtv.com.cn"                        : "1",
                "wenming.cn"                         : "1",
                "wb.lzbs.com.cn"                     : "1",
                "wallstreetcn.com"                   : "1",
                "voc.com.cn"                         : "1",
                "view.news.qq.com"                   : "1",
                "v.iqilu.com"                        : "1",
                "uschinapress.com"                   : "1",
                "tytv.com.cn"                        : "1",
                "tyrtv.com.cn"                       : "1",
                "tyrb.tynews.com.cn"                 : "1",
                "tw.people.com.cn"                   : "1",
                "tv.xmtv.cn"                         : "1",
                "tv.cntv.cn"                         : "1",
                "tv.cctv.com"                        : "1",
                "toutiao.com"                        : "1",
                "tjtv.enorth.com.cn"                 : "1",
                "titan24.com"                        : "1",
                "tibet.cn"                           : "1",
                "thepaper.cn"                        : "1",
                "tass.ru"                            : "1",
                "sztv.cutv.com"                      : "1",
                "sztqb.sznews.com/PC/layout"         : "1",
                "sznews.com"                         : "1",
                "szb.qzwb.com/dnzb"                  : "1",
                "szb.dlxww.com/dlrb"                 : "1",
                "sz.nxnews.net/nxrb"                 : "1",
                "sz.nxnews.net"                      : "1",
                "syxww.zjol.com.cn"                  : "1",
                "sxtvs.com"                          : "1",
                "sxrtv.com"                          : "1",
                "sxgov.cn"                           : "1",
                "sxdaily.com.cn"                     : "1",
                "sundonghua.com"                     : "1",
                "sputniknews.com"                    : "1",
                "sputniknews.cn"                     : "1",
                "sportscn.com"                       : "1",
                "sports.sohu.com"                    : "1",
                "sports.sina.com.cn"                 : "1",
                "sports.qq.com"                      : "1",
                "sports.eastday.com"                 : "1",
                "sports.163.com"                     : "1",
                "southcn.com"                        : "1",
                "sogou.com"                          : "1",
                "snrtv.com"                          : "1",
                "sjzrb.sjzdaily.com.cn"              : "1",
                "sjzntv.cn"                          : "1",
                "shzhidao.cn"                        : "1",
                "sdchina.com"                        : "1",
                "scol.com.cn"                        : "1",
                "sara.gov.cn"                        : "1",
                "rmfyb.chinacourt.org/paper"         : "1",
                "rmfyb.chinacourt.org"               : "1",
                "readmeok.com"                       : "1",
                "rbc.cn"                             : "1",
                "rb.lzbs.com.cn"                     : "1",
                "qunar.com"                          : "1",
                "qtv.com.cn"                         : "1",
                "qstheory.cn"                        : "1",
                "qjwb.zjol.com.cn"                   : "1",
                "qiuyi.cn"                           : "1",
                "qianlong.com"                       : "1",
                "qguiyang.com"                       : "1",
                "pingpang.info"                      : "1",
                "people.com.cn"                      : "1",
                "pcpop.com"                          : "1",
                "pcbaby.com.cn"                      : "1",
                "paper.people.com.cn/rmrbhwb"        : "1",
                "paper.people.com.cn/rmrb"           : "1",
                "paper.people.com.cn"                : "1",
                "paper.jyb.cn/zgjyb"                 : "1",
                "paper.fnews.cc"                     : "1",
                "paper.cnwomen.com.cn"               : "1",
                "paper.cnii.com.cn/rmydb"            : "1",
                "paper.ce.cn"                        : "1",
                "oceanol.com"                        : "1",
                "nxnews.net"                         : "1",
                "nntv.cn"                            : "1",
                "njrb.njdaily.cn/njrb"               : "1",
                "njgb.com"                           : "1",
                "nh.cnnb.com.cn"                     : "1",
                "newssc.org"                         : "1",
                "newspaper.jfdaily.com/jfrb"         : "1",
                "newspaper.jcrb.com"                 : "1",
                "newspaper.dbw.cn"                   : "1",
                "news18a.com"                        : "1",
                "news.xmnn.cn/xmnn"                  : "1",
                "news.xinhuanet.com"                 : "1",
                "news.tom.com"                       : "1",
                "news.sina.com.cn"                   : "1",
                "news.sdinfo.net"                    : "1",
                "news.qq.com"                        : "1",
                "news.ifeng.com/mil/"                : "1",
                "news.ifeng.com/history"             : "1",
                "news.ifeng.com"                     : "1",
                "news.hljtv.com"                     : "1",
                "news.hainan.net"                    : "1",
                "news.ebc.net.tw"                    : "1",
                "news.cnwest.com"                    : "1",
                "news.cntv.cn"                       : "1",
                "news.chinaso.com"                   : "1",
                "news.china.com/history"             : "1",
                "news.china.com"                     : "1",
                "news.cenews.com.cn"                 : "1",
                "news.cctv.com"                      : "1",
                "news.21cn.com"                      : "1",
                "news.163.com"                       : "1",
                "newpaper.dahe.cn/hnrb"              : "1",
                "nen.com.cn"                         : "1",
                "nbtv.cn"                            : "1",
                "nbs.cn"                             : "1",
                "my399.com"                          : "1",
                "morningpost.com.cn"                 : "1",
                "money.163.com"                      : "1",
                "moe.gov.cn"                         : "1",
                "mini.eastday.com"                   : "1",
                "military.china.com"                 : "1",
                "mil.huanqiu.com"                    : "1",
                "medlive.cn"                         : "1",
                "media.workercn.cn"                  : "1",
                "m.sina.com.cn"                      : "1",
                "lwdf.cn"                            : "1",
                "lnd.com.cn"                         : "1",
                "labournews.com.cn"                  : "1",
                "kankanews.com"                      : "1",
                "k618.cn"                            : "1",
                "jynews.zjol.com.cn"                 : "1",
                "jxntv.cn"                           : "1",
                "jxnews.com.cn"                      : "1",
                "jxedt.com"                          : "1",
                "jxcn.cn"                            : "1",
                "jschina.com.cn"                     : "1",
                "jntv.ijntv.cn"                      : "1",
                "jnsb.e23.cn"                        : "1",
                "jnradio.ijntv.cn"                   : "1",
                "jlwb.njnews.cn"                     : "1",
                "jkb.com.cn"                         : "1",
                "jingji.cctv.com"                    : "1",
                "jilin.com.cn"                       : "1",
                "jiaodong.net"                       : "1",
                "jcrb.com"                           : "1",
                "item.btime.com"                     : "1",
                "it168.com"                          : "1",
                "iqilu.com"                          : "1",
                "inewsweek.cn"                       : "1",
                "ijntv.cn"                           : "1",
                "ifensi.com"                         : "1",
                "ifeng.com"                          : "1",
                "iaudit.cn"                          : "1",
                "hupu.com"                           : "1",
                "huanqiu.com"                        : "1",
                "http://hzdaily.hangzhou.com.cn/dskb": "1",
                "hsb.hsw.cn"                         : "1",
                "hrbtv.net"                          : "1",
                "hprc.org.cn"                        : "1",
                "hntv.tv"                            : "1",
                "hnrb.voc.com.cn/hnrb_epaper"        : "1",
                "hnrb.voc.com.cn"                    : "1",
                "hnrb.hinews.cn"                     : "1",
                "hnr.cn"                             : "1",
                "hnntv.cn"                           : "1",
                "hljtv.com"                          : "1",
                "hkbtv.cn"                           : "1",
                "history.sohu.com"                   : "1",
                "hinews.cn"                          : "1",
                "hfbtv.com"                          : "1",
                "hebtv.com"                          : "1",
                "hebradio.com"                       : "1",
                "hebnews.cn"                         : "1",
                "hebei.com.cn"                       : "1",
                "hbrb.cnhubei.com/HTML/hbrb"         : "1",
                "hbrb.cnhubei.com"                   : "1",
                "hangzhou.com.cn"                    : "1",
                "haiwainet.cn"                       : "1",
                "gztv.com"                           : "1",
                "gzstv.com"                          : "1",
                "gxtv.cn"                            : "1",
                "gxnews.com.cn"                      : "1",
                "gscn.com.cn"                        : "1",
                "gooooal.com"                        : "1",
                "gog.cn"                             : "1",
                "gmw.cn"                             : "1",
                "gdtv.cn"                            : "1",
                "gaokao.chsi.com.cn"                 : "1",
                "gansudaily.com.cn"                  : "1",
                "forum.home.news.cn"                 : "1",
                "fjsen.com"                          : "1",
                "fjrb.fjsen.com/fjrb"                : "1",
                "fjrb.fjsen.com"                     : "1",
                "fh21.com.cn"                        : "1",
                "fblife.com"                         : "1",
                "faxuan.net"                         : "1",
                "familydoctor.com.cn"                : "1",
                "fabao365.com"                       : "1",
                "epaper.xiancn.com/newxawb"          : "1",
                "epaper.xiancn.com/newxarb"          : "1",
                "epaper.xiancn.com"                  : "1",
                "epaper.tibet3.com/xhdsb"            : "1",
                "epaper.tibet3.com/qhrb"             : "1",
                "epaper.tianjinwe.com"               : "1",
                "epaper.syd.com.cn/sywb"             : "1",
                "epaper.syd.com.cn/syrb"             : "1",
                "epaper.sxrb.com"                    : "1",
                "epaper.scdaily.cn"                  : "1",
                "epaper.qlwb.com.cn/qlwb"            : "1",
                "epaper.oeeee.com/epaper"            : "1",
                "epaper.oeeee.com"                   : "1",
                "epaper.nhaidu.com"                  : "1",
                "epaper.lnd.com.cn/paper/lswb"       : "1",
                "epaper.lnd.com.cn/paper/lnrb"       : "1",
                "epaper.jwb.com.cn/jwb"              : "1",
                "epaper.hilizi.com"                  : "1",
                "epaper.hf365.com/hfwb"              : "1",
                "epaper.gywb.cn/gyrb"                : "1",
                "epaper.gmw.cn"                      : "1",
                "epaper.cqrb.cn/html/cqrb"           : "1",
                "epaper.bjnews.com.cn"               : "1",
                "epaper.bingtuannet.com"             : "1",
                "epaper.anhuinews.com/html/ahrb"     : "1",
                "eol.cn"                             : "1",
                "enorth.com.cn"                      : "1",
                "elong.com"                          : "1",
                "edu.china.com.cn"                   : "1",
                "edition.cnn.com"                    : "1",
                "eastday.com"                        : "1",
                "e.thecover.cn/shtml"                : "1",
                "e.thecover.cn"                      : "1",
                "dota2.uuu9.com"                     : "1",
                "dltv.cn"                            : "1",
                "dbw.cn"                             : "1",
                "dayoo.com"                          : "1",
                "dangjian.cn"                        : "1",
                "dailyqd.com"                        : "1",
                "daily.cnnb.com.cn/nbrb"             : "1",
                "daily.clzg.cn"                      : "1",
                "dahe.cn"                            : "1",
                "ctax.org.cn"                        : "1",
                "cssn.cn"                            : "1",
                "cqwb.com.cn"                        : "1",
                "cqnews.net"                         : "1",
                "cpnn.com.cn"                        : "1",
                "cpd.com.cn"                         : "1",
                "cpc.people.com.cn/GB/64162/"        : "1",
                "cnwest.com"                         : "1",
                "cntheory.com"                       : "1",
                "cnr.cn"                             : "1",
                "cnnb.com.cn"                        : "1",
                "cnjiwang.com"                       : "1",
                "cnhubei.com"                        : "1",
                "cnbeta.com"                         : "1",
                "cn.nikkei.com"                      : "1",
                "cn.chinadaily.com.cn"               : "1",
                "cjrb.cjn.cn"                        : "1",
                "cjn.cn"                             : "1",
                "chosun.com"                         : "1",
                "chinese.yonhapnews.co.kr"           : "1",
                "chinaplus.cri.cn"                   : "1",
                "chinanews.com"                      : "1",
                "chinadevelopment.com.cn"            : "1",
                "chinabyte.com"                      : "1",
                "china.com.cn"                       : "1",
                "chetxia.com"                        : "1",
                "chengdu.cn"                         : "1",
                "chbcnet.com"                        : "1",
                "cet.com.cn"                         : "1",
                "ceh.com.cn"                         : "1",
                "ce.cn"                              : "1",
                "cdbs.cditv.cn"                      : "1",
                "ccwb.1news.cc"                      : "1",
                "cctv.com"                           : "1",
                "cctv.cn"                            : "1",
                "ccrb.1news.cc"                      : "1",
                "cass.cn"                            : "1",
                "cankaoxiaoxi.com"                   : "1",
                "caixin.com"                         : "1",
                "cac.gov.cn"                         : "1",
                "btime.com"                          : "1",
                "bjwb.bjd.com.cn"                    : "1",
                "bjrb.bjd.com.cn"                    : "1",
                "bbs.tianya.cn"                      : "1",
                "bbrtv.com"                          : "1",
                "banyuetan.org"                      : "1",
                "badmintoncn.com"                    : "1",
                "autohome.com.cn"                    : "1",
                "auto.sohu.com"                      : "1",
                "aoyou.com"                          : "1",
                "anhuinews.com"                      : "1",
                "7m.com.cn"                          : "1",
                "71.cn"                              : "1",
                "67.com"                             : "1",
                "58che.com"                          : "1",
                "52che.com"                          : "1",
                "51cto.com"                          : "1",
                "500.com"                            : "1",
                "40.com.cn"                          : "1",
                "315che.com"                         : "1",
                "163.com"                            : "1",
                "12371.cn"                           : "1"
        ]
        def weixinMap = [
                "郑州晚报"            : "2",
                "中国组织人事报"         : "2",
                "证券日报之声"          : "2",
                "中国青年报"           : "2",
                "福视悦动"            : "2",
                "浙江日报有风来"         : "2",
                "语文报社"            : "2",
                "紫光阁微平台"          : "2",
                "枣庄市民热线"          : "2",
                "狮说新语"            : "2",
                "燕赵晚报"            : "2",
                "云南日报"            : "2",
                "第一财经"            : "2",
                "玉环新闻"            : "2",
                "西宁晚报"            : "2",
                "新民周刊"            : "2",
                "新民晚报"            : "2",
                "厦门广电"            : "2",
                "新疆日报"            : "2",
                "俄罗斯龙报"           : "2",
                "新华日报"            : "2",
                "消费日报网"           : "2",
                "在武义"             : "2",
                "郑州电视台"           : "2",
                "株洲新闻网"           : "2",
                "资阳日报"            : "2",
                "微竹溪"             : "2",
                "中文书刊网"           : "2",
                "组织人事报"           : "2",
                "昭通日报"            : "2",
                "城市零距离"           : "2",
                "海博TV"            : "2",
                "浙江卫视中国蓝"         : "2",
                "浙江在线"            : "2",
                "张家口日报"           : "2",
                "浙江发布"            : "2",
                "中华中医网"           : "2",
                "张掖网"             : "2",
                "中国商报广西记者站"       : "2",
                "中国喀什网"           : "2",
                "中国交通报"           : "2",
                "贾生看金融"           : "2",
                "江南都市报抚州新闻"       : "2",
                "玉溪新闻"            : "2",
                "玉林新闻"            : "2",
                "云网"              : "2",
                "云南网"             : "2",
                "育路教育"            : "2",
                "云南广播电视台"         : "2",
                "伊犁日报"            : "2",
                "营口之窗"            : "2",
                "一点资讯"            : "2",
                "运河网"             : "2",
                "中汽亚讯"            : "2",
                "黄河网"             : "2",
                "羊城晚报"            : "2",
                "金羊网"             : "2",
                "银川广播电视网"         : "2",
                "银川电视台新闻开讲"       : "2",
                "养生之道网"           : "2",
                "雅虎国际贸易平台"        : "2",
                "寻医问药"            : "2",
                "邢台网"             : "2",
                "西宁广播电视台"         : "2",
                "厦门日报"            : "2",
                "厦门网"             : "2",
                "新疆阿克苏市广播电视台"     : "2",
                "新疆人民广播电台直播新疆"    : "2",
                "新疆亚欧网"           : "2",
                "新华军事网"           : "2",
                "新华网"             : "2",
                "新华社"             : "2",
                "邢台发布"            : "2",
                "新车评"             : "2",
                "西陆网"             : "2",
                "现代快报"            : "2",
                "乌有之乡网"           : "2",
                "无锡新传媒"           : "2",
                "中工网"             : "2",
                "工人日报"            : "2",
                "中国妇女"            : "2",
                "今日武进"            : "2",
                "万车网"             : "2",
                "中国天气网"           : "2",
                "华西都市报"           : "2",
                "西藏举报"            : "2",
                "健康一线"            : "2",
                "湖南日报"            : "2",
                "华夏经纬网"           : "2",
                "联合国"             : "2",
                "太原日报"            : "2",
                "科技世界网"           : "2",
                "天天养生"            : "2",
                "环球旅讯"            : "2",
                "第一旅游网"           : "2",
                "中国通辽网"           : "2",
                "平安桐庐"            : "2",
                "铜陵新闻网"           : "2",
                "时代周报"            : "2",
                "网信天津"            : "2",
                "天津日报"            : "2",
                "天津广播"            : "2",
                "英国万事通"           : "2",
                "澎湃新闻"            : "2",
                "新京报"             : "2",
                "新桐城"             : "2",
                "青年公社go"          : "2",
                "深圳晚报"            : "2",
                "深圳新闻网"           : "2",
                "沈阳网"             : "2",
                "神木新闻"            : "2",
                "山西网络广播电视台"       : "2",
                "山西广播电视台"         : "2",
                "山西日报"            : "2",
                "山西新闻网"           : "2",
                "山西晚报"            : "2",
                "吕梁新闻联播"          : "2",
                "韩城新闻网"           : "2",
                "三峡讯"             : "2",
                "SUV汽车网"          : "2",
                "苏州新闻网"           : "2",
                "星岛环球网"           : "2",
                "科技日报"            : "2",
                "大美上饶"            : "2",
                "拉瓜社区"            : "2",
                "南方新闻网"           : "2",
                "搜狐"              : "2",
                "上海发布"            : "2",
                "新浪新闻"            : "2",
                "深圳之窗"            : "2",
                "山西省原平市人民政府"      : "2",
                "平原时讯"            : "2",
                "国家发改委"           : "2",
                "鲁网"              : "2",
                "同心东阿"            : "2",
                "四川广电网络广元分公司"     : "2",
                "内江新闻网"           : "2",
                "三秦都市报"           : "2",
                "人民论坛网"           : "2",
                "天津滨海广播"          : "2",
                "泉州网"             : "2",
                "爱上渠县"            : "2",
                "青年时报"            : "2",
                "齐鲁晚报"            : "2",
                "曲靖新闻综合广播"        : "2",
                "青岛新闻网"           : "2",
                "前瞻网"             : "2",
                "青海新闻网"           : "2",
                "秦皇岛新闻网"          : "2",
                "青海广电"            : "2",
                "视讯青海"            : "2",
                "贵州民进"            : "2",
                "你好祁东"            : "2",
                "好奇心日报"           : "2",
                "莆田新闻"            : "2",
                "人民铁道网"           : "2",
                "人民中国"            : "2",
                "瞭望"              : "2",
                "欧洲时报内参"          : "2",
                "瞧纽约"             : "2",
                "宁夏网络广播电视台"       : "2",
                "宁夏新闻广播"          : "2",
                "宁夏广电新闻中心"        : "2",
                "南宁晚报"            : "2",
                "南宁日报"            : "2",
                "南宁新闻网"           : "2",
                "爱播"              : "2",
                "内蒙古晨报"           : "2",
                "南京人民广播电台"        : "2",
                "南京日报"            : "2",
                "健康中国"            : "2",
                "南国早报"            : "2",
                "南风窗"             : "2",
                "宜春日报"            : "2",
                "这里是美国"           : "2",
                "宁德电视台"           : "2",
                "宁波来发"            : "2",
                "每日经济新闻"          : "2",
                "文明泰州"            : "2",
                "绵阳日报社"           : "2",
                "闽西日报"            : "2",
                "北京晨报"            : "2",
                "商务部门户网站"         : "2",
                "财政部"             : "2",
                "教育部关工委"          : "2",
                "周末画报"            : "2",
                "今日闽南"            : "2",
                "茂名网微茂名"          : "2",
                "金属废料网"           : "2",
                "邹城发布"            : "2",
                "梅州网"             : "2",
                "四月网"             : "2",
                "爱兰州发布"           : "2",
                "泸州新闻网"           : "2",
                "连云港日报"           : "2",
                "六安新闻网"           : "2",
                "中国微蓝山"           : "2",
                "凉山日报微报"          : "2",
                "微临泉949"          : "2",
                "辽宁日报"            : "2",
                "时事军事"            : "2",
                "漯河名城网"           : "2",
                "乐山新闻网"           : "2",
                "法制网"             : "2",
                "指间利川"            : "2",
                "美好琅琊"            : "2",
                "威讯网"             : "2",
                "来凤新闻"            : "2",
                "第一昆山"            : "2",
                "昆明人民广播电台"        : "2",
                "昆明广播电视台"         : "2",
                "共工资讯网"           : "2",
                "科普中国"            : "2",
                "朝鲜窗"             : "2",
                "晋中新闻网"           : "2",
                "荆州新闻网"           : "2",
                "嘉峪关日报"           : "2",
                "中国教育新闻网"         : "2",
                "泾县新闻网"           : "2",
                "大江网"             : "2",
                "今晚海外网"           : "2",
                "中国军视网"           : "2",
                "东方圣城网"           : "2",
                "吉林人民广播电台"        : "2",
                "吉林电视台"           : "2",
                "吉林网络广播电视台"       : "2",
                "大河健康报"           : "2",
                "健康报"             : "2",
                "经济参考报"           : "2",
                "解放日报"            : "2",
                "检查日报"            : "2",
                "IT时代网"           : "2",
                "山东人民广播电台"        : "2",
                "银河网"             : "2",
                "南方周末"            : "2",
                "i黑马"             : "2",
                "长沙晚报"            : "2",
                "中国企业家杂志"         : "2",
                "海峡网"             : "2",
                "霍山县公安局政务新闻宣传"    : "2",
                "惠州新闻"            : "2",
                "花边星闻"            : "2",
                "衡水日报社"           : "2",
                "环球人物"            : "2",
                "独秀怀宁"            : "2",
                "哈尔滨广播电视台"        : "2",
                "龙广听友网"           : "2",
                "通说"              : "2",
                "呼和浩特新闻网"         : "2",
                "黄冈日报"            : "2",
                "河南日报"            : "2",
                "海城新闻"            : "2",
                "郧阳网"             : "2",
                "硒都发布"            : "2",
                "好大夫在线"           : "2",
                "汉中新闻趣事"          : "2",
                "贵阳政协"            : "2",
                "本地生活帮"           : "2",
                "贵州发布"            : "2",
                "广元新闻"            : "2",
                "广西新闻网"           : "2",
                "学国学网"            : "2",
                "观察者网"            : "2",
                "甘肃小新"            : "2",
                "绿色中国"            : "2",
                "中国政府网"           : "2",
                "金黔在线"            : "2",
                "多彩贵州网"           : "2",
                "客家新闻网"           : "2",
                "光明网"             : "2",
                "各界新闻网"           : "2",
                "贵港宣传"            : "2",
                "跟谁学"             : "2",
                "广东电台"            : "2",
                "今日广德"            : "2",
                "甘谷生活圈"           : "2",
                "富阳发布"            : "2",
                "阜新宣传"            : "2",
                "复兴网"             : "2",
                "天水男健放心医苑"        : "2",
                "FT中文网"           : "2",
                "新福清"             : "2",
                "看福清"             : "2",
                "佛山新闻网"           : "2",
                "财富中文网"           : "2",
                "外交小灵通"           : "2",
                "福建泉港广电网络"        : "2",
                "福建电视台综合频道"       : "2",
                "东南网播报"           : "2",
                "清流新闻"            : "2",
                "金融时报"            : "2",
                "凤县新闻"            : "2",
                "中国农业新闻"          : "2",
                "余杭晨报"            : "2",
                "恩施新闻网"           : "2",
                "经济观察网"           : "2",
                "中国教育网络"          : "2",
                "亿邦动力网"           : "2",
                "衡阳新闻网"           : "2",
                "达州新闻"            : "2",
                "大众网"             : "2",
                "大众日报"            : "2",
                "洞头发布"            : "2",
                "东南快报"            : "2",
                "大连日报"            : "2",
                "新闻大连"            : "2",
                "德化网"             : "2",
                "当代先锋网"           : "2",
                "党建网微平台"          : "2",
                "青岛日报"            : "2",
                "浙江新闻"            : "2",
                "浙江新闻频道"          : "2",
                "沧州发布"            : "2",
                "长汀网"             : "2",
                "沈阳网络广播电视"        : "2",
                "常熟日报微报"          : "2",
                "长沙广电"            : "2",
                "中国证券报"           : "2",
                "中评社"             : "2",
                "重庆晚报"            : "2",
                "重庆日报"            : "2",
                "中国质量新闻网"         : "2",
                "重庆晨报"            : "2",
                "中国警察网"           : "2",
                "常宁每日新闻"          : "2",
                "苍南新闻网"           : "2",
                "央视网"             : "2",
                "中国旅游网"           : "2",
                "中国证券网"           : "2",
                "中国之声"            : "2",
                "强国网"             : "2",
                "中国宁波网"           : "2",
                "中国信息产业网"         : "2",
                "湖北日报网"           : "2",
                "荆楚网"             : "2",
                "湖北日报"            : "2",
                "健康界"             : "2",
                "武汉晚报"            : "2",
                "长江日报"            : "2",
                "汉网"              : "2",
                "楚网"              : "2",
                "中国汽车报"           : "2",
                "中国劳动保障报"         : "2",
                "长江网"             : "2",
                "中国工商报"           : "2",
                "春雨健康"            : "2",
                "池州新闻网"           : "2",
                "美國國際日報"          : "2",
                "吴忠日报"            : "2",
                "中国水利网"           : "2",
                "投中国"             : "2",
                "价值中国"            : "2",
                "中国贸易新闻"          : "2",
                "西藏发布"            : "2",
                "中国侨网"            : "2",
                "中国邮政报"           : "2",
                "中国建设报"           : "2",
                "NGO招聘"           : "2",
                "中国日报"            : "2",
                "中国日报中文网"         : "2",
                "长春广播电视台"         : "2",
                "宇博智库"            : "2",
                "车讯网"             : "2",
                "车问网"             : "2",
                "内蒙古晨报赤峰新闻"       : "2",
                "中国改革报"           : "2",
                "中国财经报"           : "2",
                "中国经济周刊"          : "2",
                "IT经理世界"          : "2",
                "中国教育电视台三频道"      : "2",
                "经济日报"            : "2",
                "成都日报"            : "2",
                "文明成都"            : "2",
                "百姓生活网"           : "2",
                "长寿日报"            : "2",
                "中国煤炭报"           : "2",
                "中央纪律监察部网站"       : "2",
                "中国经营报"           : "2",
                "参考消息"            : "2",
                "政府采购信息"          : "2",
                "内蒙古晨报巴彦淖尔新闻"     : "2",
                "北京电视台"           : "2",
                "西双版纳报"           : "2",
                "保康镇政府"           : "2",
                "芝麻匠通讯社"          : "2",
                "昌平圈"             : "2",
                "北京周报"            : "2",
                "首都之窗"            : "2",
                "蚌埠日报"            : "2",
                "包头新闻网"           : "2",
                "宝宝树"             : "2",
                "中国审计报"           : "2",
                "中国安全生产网"         : "2",
                "文明安庆"            : "2",
                "安丘广电"            : "2",
                "安徽日报"            : "2",
                "中安在线"            : "2",
                "阿勒泰新闻网"          : "2",
                "爱思想网"            : "2",
                "安徽网络广播电视台"       : "2",
                "今日宿松"            : "2",
                "微阿坝"             : "2",
                "99健康网"           : "2",
                "绿野中国户外网甘肃绿野户外俱乐部": "2",
                "宣讲家网"            : "2",
                "卡车之家"            : "2",
                "锦州新闻网"           : "2",
                "岳阳广播电视台"         : "2",
                "环京津新闻网"          : "2",
                "人民网"             : "2",
                "温岭广电新闻"          : "2",
                "黄鹤云"             : "2",
                "中国文明网"           : "2",
                "兰州晚报"            : "2",
                "华尔街见闻"           : "2",
                "华声在线"            : "2",
                "今日话题"            : "2",
                "山东广播电视台"         : "2",
                "美国侨报"            : "2",
                "太原在线网"           : "2",
                "今日头条"            : "2",
                "天津滨海广播电视台官微"     : "2",
                "中国西藏网"           : "2",
                "塔斯社TASS北京分社"     : "2",
                "深圳发布"            : "2",
                "深圳特区报"           : "2",
                "东南早报"            : "2",
                "宁夏日报"            : "2",
                "松阳新闻"            : "2",
                "陕西广播电视台"         : "2",
                "山西黄河新闻网"         : "2",
                "陕西传媒网"           : "2",
                "俄罗斯SputnikNews"  : "2",
                "搜狐新闻"            : "2",
                "石家庄日报"           : "2",
                "石家庄广播电视台"        : "2",
                "生活报"             : "2",
                "中国山东网"           : "2",
                "四川在线"            : "2",
                "人民法院报"           : "2",
                "山东商报"            : "2",
                "北京电台RBC"         : "2",
                "兰州日报"            : "2",
                "爱青岛"             : "2",
                "求是网"             : "2",
                "钱江晚报"            : "2",
                "求医网"             : "2",
                "千龙网"             : "2",
                "贵阳发布"            : "2",
                "太平洋亲子网"          : "2",
                "人民日报海外版欧洲刊"      : "2",
                "人民日报"            : "2",
                "中国教育报"           : "2",
                "中国妇女报"           : "2",
                "人民邮电报"           : "2",
                "观沧海"             : "2",
                "宁夏新闻网"           : "2",
                "南宁人民广播电台"        : "2",
                "南宁电视台"           : "2",
                "宁海新闻网"           : "2",
                "四川新闻网"           : "2",
                "黑龙江晨报"           : "2",
                "网通社"             : "2",
                "新华每日电讯"          : "2",
                "齐鲁热线"            : "2",
                "腾讯新闻"            : "2",
                "凤凰网军事"           : "2",
                "凤凰新闻客户端"         : "2",
                "黑龙江电视台"          : "2",
                "海南在线"            : "2",
                "国搜新闻"            : "2",
                "中华网"             : "2",
                "中国环境报"           : "2",
                "中国环境新闻"          : "2",
                "央视新闻"            : "2",
                "21CN微企云"         : "2",
                "网易新闻"            : "2",
                "东北新闻网"           : "2",
                "浙里宁波"            : "2",
                "南京广播电视台"         : "2",
                "哈尔滨新闻网"          : "2",
                "微言教育"            : "2",
                "东方头条资讯"          : "2",
                "中华网军事"           : "2",
                "环球军事"            : "2",
                "医脉通"             : "2",
                "瞭望东方周刊"          : "2",
                "北国网"             : "2",
                "看看新闻Knews"       : "2",
                "未来网"             : "2",
                "缙云播报"            : "2",
                "江西网络台"           : "2",
                "驾校管理网"           : "2",
                "中国江苏网"           : "2",
                "济南广播电视台"         : "2",
                "济南时报"            : "2",
                "金陵晚报"            : "2",
                "央视财经"            : "2",
                "中国彩虹网"           : "2",
                "胶东在线"            : "2",
                "正义网"             : "2",
                "齐鲁网"             : "2",
                "中国新闻周刊"          : "2",
                "凤凰网"             : "2",
                "华人环球网"           : "2",
                "环球时报"            : "2",
                "都市快报"            : "2",
                "华商报"             : "2",
                "河南电视台"           : "2",
                "海南日报"            : "2",
                "映象网"             : "2",
                "海南网络广播电视台"       : "2",
                "黑龙江网络广播电视台"      : "2",
                "海口广播电视台"         : "2",
                "南海网"             : "2",
                "合肥发布"            : "2",
                "合肥市广播电视台"        : "2",
                "河北广播电视台"         : "2",
                "河北日报"            : "2",
                "长城网"             : "2",
                "杭州网"             : "2",
                "广视网"             : "2",
                "人民网贵州频道"         : "2",
                "动静贵州"            : "2",
                "广西广电网络北海分公司"     : "2",
                "广西法治日报"          : "2",
                "中国甘肃网"           : "2",
                "广东广播电视台今日最新闻"    : "2",
                "阳光高考信息平台"        : "2",
                "每日甘肃"            : "2",
                "华音阁"             : "2",
                "福建微尤溪"           : "2",
                "福建日报"            : "2",
                "飞华健康"            : "2",
                "越野e族社区"          : "2",
                "家庭医生在线"          : "2",
                "西安晚报"            : "2",
                "西安日报"            : "2",
                "西海都市报"           : "2",
                "青报新媒"            : "2",
                "沈阳晚报"            : "2",
                "沈阳日报"            : "2",
                "四川日报"            : "2",
                "南方都市报"           : "2",
                "海南新闻频道"          : "2",
                "辽沈晚报"            : "2",
                "今晚报"             : "2",
                "半岛晨报"            : "2",
                "合肥晚报"            : "2",
                "贵阳日报"            : "2",
                "光明日报"            : "2",
                "兵团日报维吾尔文版"       : "2",
                "中国教育在线"          : "2",
                "北方网"             : "2",
                "中国网教育频道"         : "2",
                "CNN每日新闻"         : "2",
                "天府早报"            : "2",
                "游久DOTA2"         : "2",
                "大连好生活"           : "2",
                "大连广播电视台"         : "2",
                "牡丹江电视新闻台"        : "2",
                "东北网"             : "2",
                "大洋网"             : "2",
                "宁波日报微互动"         : "2",
                "昆明日报"            : "2",
                "大河网"             : "2",
                "中国税务报"           : "2",
                "中国社会科学网"         : "2",
                "华龙网"             : "2",
                "中国电力新闻网"         : "2",
                "西部网民生热线"         : "2",
                "理论网"             : "2",
                "央广网健康"           : "2",
                "中国吉林网"           : "2",
                "日经中文网"           : "2",
                "中国日报网站"          : "2",
                "今日朝鲜"            : "2",
                "韩联社中文网"          : "2",
                "英语环球NEWSPlus"    : "2",
                "中国新闻网"           : "2",
                "中国新闻社"           : "2",
                "中国发展网"           : "2",
                "中国网"             : "2",
                "1038车天下"         : "2",
                "成都全搜索新闻网"        : "2",
                "华广网"             : "2",
                "中国经济导报"          : "2",
                "中国经济网"           : "2",
                "成都广电网络"          : "2",
                "长春晚报"            : "2",
                "掌上长春"            : "2",
                "财新网"             : "2",
                "网信中国"            : "2",
                "网络传播杂志"          : "2",
                "北京晚报"            : "2",
                "北京日报"            : "2",
                "天涯杂谈"            : "2",
                "广西人民广播电台"        : "2",
                "半月谈"             : "2",
                "汽车之家"            : "2",
                "搜狐汽车福州站"         : "2",
                "58车"             : "2",
                "爱车秀"             : "2",
                "掌上论坛"            : "2",
                "中国汽车消费报道"        : "2"
        ]

//查询所有站点
        String start = properties.startDate
        String end = properties.endDate
        boolean searchData = false;
        searchData = Boolean.valueOf(properties.searchData)

        if (!start) {
            println '开始时间startDate不能为空'
            return
        }
        if (!end) {
            println '结束时间endDate不能为空'
            return
        }

        def sdf = new SimpleDateFormat('yyyy-MM-dd HH:mm:ss')
        Date startDate = sdf.parse(start)
        Date endDate = sdf.parse(end)
        if (!startDate) {
            println '开始时间startDate不合法'
            return
        }
        if (!endDate) {
            println '结束时间endDate不合法'
            return
        }
        List<Site> allSites = siteService.getSitesByDate(startDate, endDate);
        def hasDataMap = [:]
        List returnList = new ArrayList()
        println("无数据的域名站点查询中，请稍候……")
        println("总共" + allSites.size() + "个站点")
        for (int i = 0; i < allSites.size(); i++) {
            Site site = allSites.get(i)
            println("正在处理第" + ((i + 1) as String) + "个站点:" + site.toString())
            int siteType = site.siteType
            String websiteDomain = site.websiteDomain
            String siteName = site.siteName
            String isIncluded = "否"
            if (1 == siteType) {
                if (urlsMap.containsKey(websiteDomain)) {
                    isIncluded = "是"
                }
            }
            if (2 == siteType) {
                if (weixinMap.containsKey(siteName)) {
                    isIncluded = "是"
                }
            }

            if (hasDataMap.containsKey(websiteDomain + String.valueOf(siteType)) || hasDataMap.containsKey(siteName + String.valueOf(siteType))) {
                continue;
            }
            if (searchData) {
                String startTime = "1970-01-01 00:00:00"
                Date startBegin = sdf.parse(startTime)
                List newsList = siteRepo.getSitesNewsFromEs([site], 0, startBegin, new Date(), 0, false, 1, "", 1, 1)
                if (newsList && newsList.size() > 0) {
                    if (1 == siteType) {
                        hasDataMap.put(websiteDomain + String.valueOf(siteType), "1")
                    }
                    if (2 == siteType) {
                        hasDataMap.put(siteName + String.valueOf(siteType), "2")
                    }
                    continue;
                } else {
                    def obj = [:]
                    Account account = accountRepo.getUserById(site.userId)
                    obj.put("siteId", site.siteId)
                    obj.put("userId", site.userId)
                    obj.put("siteName", site.siteName)
                    obj.put("websiteDomain", site.websiteDomain)
                    obj.put("websiteName", site.websiteName)
                    if (!site.updateTime){
                        site.updateTime = site.createTime
                    }
                    obj.put("updateTime", DateUitl.convertStrDate(site.updateTime))
                    obj.put("siteType", site.siteType == 1 ? "网站" : "公众号")
                    obj.put("isIncluded", isIncluded)
                    String websiteDomainhttp = ""
                    String url = site.websiteDomain
                    if (url) {
                        if (url.startsWith("http")) {
                            websiteDomainhttp = url
                        } else if (url.startsWith("www")) {
                            websiteDomainhttp = "http://" + url
                        } else {
                            websiteDomainhttp = "http://www." + url
                        }
                    }
                    obj.put("websiteDomainhttp", websiteDomainhttp)
                    obj.put("message", site.message)
                    obj.put("userName", account?account.userName:"")
                    returnList.add(obj)

                    println("找到无数据的站点:" + obj.toString())
                }
            }else{
                def obj = [:]
                Account account = accountRepo.getUserById(site.userId)
                obj.put("siteId", site.siteId)
                obj.put("userId", site.userId)
                obj.put("siteName", site.siteName)
                obj.put("websiteDomain", site.websiteDomain)
                obj.put("websiteName", site.websiteName)
                if (!site.updateTime){
                    site.updateTime = site.createTime
                }
                obj.put("updateTime", DateUitl.convertStrDate(site.updateTime))
                obj.put("siteType", site.siteType == 1 ? "网站" : "公众号")
                obj.put("isIncluded", isIncluded)
                String websiteDomainhttp = ""
                String url = site.websiteDomain
                if (url) {
                    if (url.startsWith("http")) {
                        websiteDomainhttp = url
                    } else if (url.startsWith("www")) {
                        websiteDomainhttp = "http://" + url
                    } else {
                        websiteDomainhttp = "http://www." + url
                    }
                }
                obj.put("websiteDomainhttp", websiteDomainhttp)
                obj.put("message", site.message)
                obj.put("userName", account?account.userName:"")
                returnList.add(obj)
            }
        }
        String outfileName = UUID.randomUUID();
        ExportExcel ex = new ExportExcel();
        String sheetName = "查询站点";//下载文件的默认名字,sheet页名字
        String fileName = outfileName
        String headers = "siteId,userId,siteName,websiteDomain,websiteDomainhttp,updateTime,siteType,isIncluded,message,userName";
//表头
        String selname = "siteId,userId,siteName,websiteDomain,websiteDomainhttp,updateTime,siteType,isIncluded,message,userName,o"
//标题对应key值

        HSSFWorkbook wb = ex.exportExcel(sheetName, headers, returnList, selname);
//返回一个workbook即excel实例。datetime是sheet页的名称
        String excelFolder = "D:\\"+outfileName;
        def result = [
                status: HttpStatus.SC_OK,
                msg   : '',
        ];
        //如果文件夹不存在则创建，如果已经存在则删除
        File outPath = new File(excelFolder)
        if (!outPath.exists()) {
            FileUtils.forceMkdir(outPath)
        } else {
            FileUtils.forceDelete(outPath)
            FileUtils.forceMkdir(outPath)
        }
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        try {
            wb.write(os);
        }
        catch (IOException e) {
            e.printStackTrace();
            println("出现错误，请不要关闭此窗口，并联系开发工程师，谢谢")
        }
        byte[] content = os.toByteArray();
        OutputStream fos = null;
        File file = new File(excelFolder + "/" + "excel.xls")

        try {
            fos = new FileOutputStream(file);
            fos.write(content);
            os.close();
            fos.close();
        }
        catch (Exception e) {
            e.printStackTrace();
            println("出现错误，请不要关闭此窗口，并联系开发工程师，谢谢")
        }
        println("生成目录在 D:\\"+outfileName)
    }

    @Override
    public String getPropertyFileName() {
        return "sitelist_date.properties";
    }
}
